language: node_js
os:
  - linux
node_js:
  - lts/*
cache:
  - yarn
script:
  - yarn deploy
deploy:
  provider: pages
  strategy: git
  cleanup: true
  local_dir: docs/.vuepress/dist
  # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master