# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: VuePress CI

on:
  push:
    branches: [ docs ]
  # pull_request:
  #   branches: [ docs ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    # 检出仓库源码
    - uses: actions/checkout@v2
    # 指定Node版本
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    # 安装依赖、打包应用
    - run: npm install
    - run: npm run build --if-present
    # 部署阿里云
    - name: SSH Deploy-Aliyun
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USER }}
        REMOTE_PORT: ${{ secrets.SSH_PORT }}
        SOURCE: docs/.vuepress/dist
        TARGET: docs
        ARGS: "-avzr --delete"

