# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ docs ]
  pull_request:
    branches: [ docs ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      # env:
        # CI: true
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY }}
        REMOTE_HOST: 47.115.0.145
        REMOTE_USER: root
        REMOTE_PORT: 22
        SOURCE: dist/
        TARGET: /root/blog
        ARGS: -rltgoDzvO --delete # Arguments to pass to rsync

